# For more details on app.yaml, see: https://aka.ms/coral/appyaml

template: external-service
deployments:
  development:
    target: development
    clusters: 1
    values:
      image: ghcr.io/erikschlegel/coral-seed-java-api-hw:main
      port: 5000
