template: external-service
deployments:
  dev:
    target: dev
    clusters: 1
    values:
      image: ghcr.io/davesee/coral-seed-java-api-hw:main
      fqdn: newapp.contoso.com
      port: 5000
      replicas: 2
